// SPDX-License-Identifier: Apache-2.0

// Generates the JSON Schema validators in src/generated/ from spec/schema/ with Ajv's
// standalone code generation, so that no schema is compiled at run time: compiling uses
// new Function, which a Content Security Policy without 'unsafe-eval' forbids.
// Usage: node scripts/generate-validators.ts (sync-spec.ts runs it after every sync).
// test/validators.test.ts fails if the committed files differ from what this generates.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Ajv2020 } from "ajv/dist/2020.js";
import { _ } from "ajv/dist/compile/codegen/index.js";
import standalone from "ajv/dist/standalone/index.js";
import { formats } from "../src/schema-runtime.ts";

const ROOT = join(import.meta.dirname, "..");

interface Target {
  schema: string;
  exportName: string;
  output: string;
}

const TARGETS: readonly Target[] = [
  { schema: "spec/schema/mandate-v0.schema.json", exportName: "validateMandate", output: "src/generated/mandate-validator.ts" },
  { schema: "spec/schema/audit-v0.schema.json", exportName: "validateAudit", output: "src/generated/audit-validator.ts" },
];

// Ajv refers to its run-time helpers as CommonJS modules; they are replaced with the
// equivalents in src/schema-runtime.ts.
const RUNTIME: Readonly<Record<string, string>> = {
  'require("ajv/dist/runtime/ucs2length").default': "ucs2length",
  'require("ajv/dist/runtime/equal").default': "equal",
};

function header(target: Target): string {
  return [
    "// SPDX-License-Identifier: Apache-2.0",
    `// Generated by scripts/generate-validators.ts from ${target.schema}; do not edit.`,
    "// @ts-nocheck",
    'import { equal, formats, ucs2length } from "../schema-runtime.ts";',
    "",
  ].join("\n");
}

function generate(target: Target): string {
  const ajv = new Ajv2020({
    strict: false,
    allErrors: false,
    formats: { ...formats },
    code: { source: true, esm: true, lines: true, formats: _`formats` },
  });
  ajv.addSchema(JSON.parse(readFileSync(join(ROOT, target.schema), "utf8")) as object, target.exportName);
  let code = standalone.default(ajv, { [target.exportName]: target.exportName }).replace(/^"use strict";\n/, "");
  for (const [reference, name] of Object.entries(RUNTIME)) code = code.replaceAll(reference, name);
  if (/\brequire\(/.test(code)) throw new Error(`${target.output}: unexpected run-time dependency in the generated code`);
  return header(target) + code + (code.endsWith("\n") ? "" : "\n");
}

/** The generated validator modules, by path relative to the repository. */
export function generateValidators(): Map<string, string> {
  return new Map(TARGETS.map((t) => [t.output, generate(t)]));
}

export function writeValidators(): void {
  for (const [path, code] of generateValidators()) writeFileSync(join(ROOT, path), code);
}

if ((import.meta as { main?: boolean }).main) {
  writeValidators();
  console.log(`src/generated/: ${TARGETS.length} validators`);
}
